module Model/Private/Elasticsearch.Types.AccountTrustRelationship where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Model/Private/Elasticsearch.Common
data AccountTrustRelationship
instance Show AccountTrustRelationship
instance Eq AccountTrustRelationship
instance FromJSON AccountTrustRelationship
instance ToJSON AccountTrustRelationship
