-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema CertificateMetaData
module Model/Private/Elasticsearch.Types.CertificateMetaData where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Model/Private/Elasticsearch.Common
import Model/Private/Elasticsearch.TypeAlias

-- | Defines the object schema located at @components.schemas.CertificateMetaData@ in the specification.
-- 
-- The certificate MetaData
data CertificateMetaData = CertificateMetaData {
  -- | fingerprint: The fingerprint of the certificate
  certificateMetaDataFingerprint :: Data.Text.Internal.Text
  -- | valid_from: The valid from date of the certificate in UTC
  , certificateMetaDataValidFrom :: Data.Text.Internal.Text
  -- | valid_to: The expiry date of the certificate in UTC
  , certificateMetaDataValidTo :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON CertificateMetaData
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["fingerprint" Data.Aeson.Types.ToJSON..= certificateMetaDataFingerprint obj] : ["valid_from" Data.Aeson.Types.ToJSON..= certificateMetaDataValidFrom obj] : ["valid_to" Data.Aeson.Types.ToJSON..= certificateMetaDataValidTo obj] : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["fingerprint" Data.Aeson.Types.ToJSON..= certificateMetaDataFingerprint obj] : ["valid_from" Data.Aeson.Types.ToJSON..= certificateMetaDataValidFrom obj] : ["valid_to" Data.Aeson.Types.ToJSON..= certificateMetaDataValidTo obj] : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON CertificateMetaData
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "CertificateMetaData" (\obj -> ((GHC.Base.pure CertificateMetaData GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "fingerprint")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "valid_from")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "valid_to"))
-- | Create a new 'CertificateMetaData' with all required fields.
mkCertificateMetaData :: Data.Text.Internal.Text -- ^ 'certificateMetaDataFingerprint'
  -> Data.Text.Internal.Text -- ^ 'certificateMetaDataValidFrom'
  -> Data.Text.Internal.Text -- ^ 'certificateMetaDataValidTo'
  -> CertificateMetaData
mkCertificateMetaData certificateMetaDataFingerprint certificateMetaDataValidFrom certificateMetaDataValidTo = CertificateMetaData{certificateMetaDataFingerprint = certificateMetaDataFingerprint,
                                                                                                                                   certificateMetaDataValidFrom = certificateMetaDataValidFrom,
                                                                                                                                   certificateMetaDataValidTo = certificateMetaDataValidTo}
