-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema DeploymentCreateSettings
module Model/Private/Elasticsearch.Types.DeploymentCreateSettings where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Model/Private/Elasticsearch.Common
import Model/Private/Elasticsearch.TypeAlias
import {-# SOURCE #-} Model/Private/Elasticsearch.Types.DeploymentObservabilitySettings
import {-# SOURCE #-} Model/Private/Elasticsearch.Types.TrafficFilterSettings

-- | Defines the object schema located at @components.schemas.DeploymentCreateSettings@ in the specification.
-- 
-- Additional configuration for the new deployment object.
data DeploymentCreateSettings = DeploymentCreateSettings {
  -- | observability: The observability settings for a deployment
  deploymentCreateSettingsObservability :: (GHC.Maybe.Maybe DeploymentObservabilitySettings)
  -- | traffic_filter_settings: The configuration settings for the traffic filter.
  , deploymentCreateSettingsTrafficFilterSettings :: (GHC.Maybe.Maybe TrafficFilterSettings)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON DeploymentCreateSettings
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("observability" Data.Aeson.Types.ToJSON..=)) (deploymentCreateSettingsObservability obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("traffic_filter_settings" Data.Aeson.Types.ToJSON..=)) (deploymentCreateSettingsTrafficFilterSettings obj) : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("observability" Data.Aeson.Types.ToJSON..=)) (deploymentCreateSettingsObservability obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("traffic_filter_settings" Data.Aeson.Types.ToJSON..=)) (deploymentCreateSettingsTrafficFilterSettings obj) : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON DeploymentCreateSettings
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "DeploymentCreateSettings" (\obj -> (GHC.Base.pure DeploymentCreateSettings GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "observability")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "traffic_filter_settings"))
-- | Create a new 'DeploymentCreateSettings' with all required fields.
mkDeploymentCreateSettings :: DeploymentCreateSettings
mkDeploymentCreateSettings = DeploymentCreateSettings{deploymentCreateSettingsObservability = GHC.Maybe.Nothing,
                                                      deploymentCreateSettingsTrafficFilterSettings = GHC.Maybe.Nothing}
