module Model/Private/Elasticsearch.Types.ElasticsearchScriptTypeSettings where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Model/Private/Elasticsearch.Common
data ElasticsearchScriptTypeSettings
instance Show ElasticsearchScriptTypeSettings
instance Eq ElasticsearchScriptTypeSettings
instance FromJSON ElasticsearchScriptTypeSettings
instance ToJSON ElasticsearchScriptTypeSettings
