module Model/Private/Elasticsearch.Types.ElasticsearchPlanControlConfiguration where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Model/Private/Elasticsearch.Common
data ElasticsearchPlanControlConfiguration
instance Show ElasticsearchPlanControlConfiguration
instance Eq ElasticsearchPlanControlConfiguration
instance FromJSON ElasticsearchPlanControlConfiguration
instance ToJSON ElasticsearchPlanControlConfiguration
data ElasticsearchPlanControlConfigurationClusterReboot
instance Show ElasticsearchPlanControlConfigurationClusterReboot
instance Eq ElasticsearchPlanControlConfigurationClusterReboot
instance FromJSON ElasticsearchPlanControlConfigurationClusterReboot
instance ToJSON ElasticsearchPlanControlConfigurationClusterReboot
