-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema EnterpriseSearchPlan
module Model/Private/Elasticsearch.Types.EnterpriseSearchPlan where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Model/Private/Elasticsearch.Common
import Model/Private/Elasticsearch.TypeAlias
import {-# SOURCE #-} Model/Private/Elasticsearch.Types.EnterpriseSearchConfiguration
import {-# SOURCE #-} Model/Private/Elasticsearch.Types.EnterpriseSearchTopologyElement
import {-# SOURCE #-} Model/Private/Elasticsearch.Types.TransientEnterpriseSearchPlanConfiguration

-- | Defines the object schema located at @components.schemas.EnterpriseSearchPlan@ in the specification.
-- 
-- The plan for the Enterprise Search cluster.
data EnterpriseSearchPlan = EnterpriseSearchPlan {
  -- | cluster_topology
  enterpriseSearchPlanClusterTopology :: (GHC.Maybe.Maybe ([EnterpriseSearchTopologyElement]))
  -- | enterprise_search
  , enterpriseSearchPlanEnterpriseSearch :: EnterpriseSearchConfiguration
  -- | transient: Defines configuration parameters that control how the plan (i.e. consisting of the cluster topology and Enterprise Search settings) is applied
  , enterpriseSearchPlanTransient :: (GHC.Maybe.Maybe TransientEnterpriseSearchPlanConfiguration)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON EnterpriseSearchPlan
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("cluster_topology" Data.Aeson.Types.ToJSON..=)) (enterpriseSearchPlanClusterTopology obj) : ["enterprise_search" Data.Aeson.Types.ToJSON..= enterpriseSearchPlanEnterpriseSearch obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("transient" Data.Aeson.Types.ToJSON..=)) (enterpriseSearchPlanTransient obj) : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("cluster_topology" Data.Aeson.Types.ToJSON..=)) (enterpriseSearchPlanClusterTopology obj) : ["enterprise_search" Data.Aeson.Types.ToJSON..= enterpriseSearchPlanEnterpriseSearch obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("transient" Data.Aeson.Types.ToJSON..=)) (enterpriseSearchPlanTransient obj) : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON EnterpriseSearchPlan
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "EnterpriseSearchPlan" (\obj -> ((GHC.Base.pure EnterpriseSearchPlan GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "cluster_topology")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "enterprise_search")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "transient"))
-- | Create a new 'EnterpriseSearchPlan' with all required fields.
mkEnterpriseSearchPlan :: EnterpriseSearchConfiguration -- ^ 'enterpriseSearchPlanEnterpriseSearch'
  -> EnterpriseSearchPlan
mkEnterpriseSearchPlan enterpriseSearchPlanEnterpriseSearch = EnterpriseSearchPlan{enterpriseSearchPlanClusterTopology = GHC.Maybe.Nothing,
                                                                                   enterpriseSearchPlanEnterpriseSearch = enterpriseSearchPlanEnterpriseSearch,
                                                                                   enterpriseSearchPlanTransient = GHC.Maybe.Nothing}
