module Model/Private/Elasticsearch.Types.EnterpriseSearchPlanControlConfiguration where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Model/Private/Elasticsearch.Common
data EnterpriseSearchPlanControlConfiguration
instance Show EnterpriseSearchPlanControlConfiguration
instance Eq EnterpriseSearchPlanControlConfiguration
instance FromJSON EnterpriseSearchPlanControlConfiguration
instance ToJSON EnterpriseSearchPlanControlConfiguration
data EnterpriseSearchPlanControlConfigurationClusterReboot
instance Show EnterpriseSearchPlanControlConfigurationClusterReboot
instance Eq EnterpriseSearchPlanControlConfigurationClusterReboot
instance FromJSON EnterpriseSearchPlanControlConfigurationClusterReboot
instance ToJSON EnterpriseSearchPlanControlConfigurationClusterReboot
