-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema ExternalTrustRelationship
module Model/Private/Elasticsearch.Types.ExternalTrustRelationship where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Model/Private/Elasticsearch.Common
import Model/Private/Elasticsearch.TypeAlias

-- | Defines the object schema located at @components.schemas.ExternalTrustRelationship@ in the specification.
-- 
-- The trust relationship with external entities (remote environments, remote accounts...).
data ExternalTrustRelationship = ExternalTrustRelationship {
  -- | trust_all: If true, all clusters in this external entity will be trusted and the \`trust_allowlist\` is ignored.
  externalTrustRelationshipTrustAll :: GHC.Types.Bool
  -- | trust_allowlist: The list of clusters to trust. Only used when \`trust_all\` is false.
  , externalTrustRelationshipTrustAllowlist :: (GHC.Maybe.Maybe ([Data.Text.Internal.Text]))
  -- | trust_relationship_id: the ID of the external trust relationship
  , externalTrustRelationshipTrustRelationshipId :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON ExternalTrustRelationship
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["trust_all" Data.Aeson.Types.ToJSON..= externalTrustRelationshipTrustAll obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("trust_allowlist" Data.Aeson.Types.ToJSON..=)) (externalTrustRelationshipTrustAllowlist obj) : ["trust_relationship_id" Data.Aeson.Types.ToJSON..= externalTrustRelationshipTrustRelationshipId obj] : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["trust_all" Data.Aeson.Types.ToJSON..= externalTrustRelationshipTrustAll obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("trust_allowlist" Data.Aeson.Types.ToJSON..=)) (externalTrustRelationshipTrustAllowlist obj) : ["trust_relationship_id" Data.Aeson.Types.ToJSON..= externalTrustRelationshipTrustRelationshipId obj] : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON ExternalTrustRelationship
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "ExternalTrustRelationship" (\obj -> ((GHC.Base.pure ExternalTrustRelationship GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "trust_all")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "trust_allowlist")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "trust_relationship_id"))
-- | Create a new 'ExternalTrustRelationship' with all required fields.
mkExternalTrustRelationship :: GHC.Types.Bool -- ^ 'externalTrustRelationshipTrustAll'
  -> Data.Text.Internal.Text -- ^ 'externalTrustRelationshipTrustRelationshipId'
  -> ExternalTrustRelationship
mkExternalTrustRelationship externalTrustRelationshipTrustAll externalTrustRelationshipTrustRelationshipId = ExternalTrustRelationship{externalTrustRelationshipTrustAll = externalTrustRelationshipTrustAll,
                                                                                                                                       externalTrustRelationshipTrustAllowlist = GHC.Maybe.Nothing,
                                                                                                                                       externalTrustRelationshipTrustRelationshipId = externalTrustRelationshipTrustRelationshipId}
