module Model/Private/Elasticsearch.Types.IntegrationsServerPlanControlConfiguration where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Model/Private/Elasticsearch.Common
data IntegrationsServerPlanControlConfiguration
instance Show IntegrationsServerPlanControlConfiguration
instance Eq IntegrationsServerPlanControlConfiguration
instance FromJSON IntegrationsServerPlanControlConfiguration
instance ToJSON IntegrationsServerPlanControlConfiguration
data IntegrationsServerPlanControlConfigurationClusterReboot
instance Show IntegrationsServerPlanControlConfigurationClusterReboot
instance Eq IntegrationsServerPlanControlConfigurationClusterReboot
instance FromJSON IntegrationsServerPlanControlConfigurationClusterReboot
instance ToJSON IntegrationsServerPlanControlConfigurationClusterReboot
