module Model/Private/Elasticsearch.Types.KibanaPlanControlConfiguration where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Model/Private/Elasticsearch.Common
data KibanaPlanControlConfiguration
instance Show KibanaPlanControlConfiguration
instance Eq KibanaPlanControlConfiguration
instance FromJSON KibanaPlanControlConfiguration
instance ToJSON KibanaPlanControlConfiguration
data KibanaPlanControlConfigurationClusterReboot
instance Show KibanaPlanControlConfigurationClusterReboot
instance Eq KibanaPlanControlConfigurationClusterReboot
instance FromJSON KibanaPlanControlConfigurationClusterReboot
instance ToJSON KibanaPlanControlConfigurationClusterReboot
