-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema MetadataItem
module Model/Private/Elasticsearch.Types.MetadataItem where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Model/Private/Elasticsearch.Common
import Model/Private/Elasticsearch.TypeAlias

-- | Defines the object schema located at @components.schemas.MetadataItem@ in the specification.
-- 
-- The key-value pair.
data MetadataItem = MetadataItem {
  -- | key: The metadata field name
  metadataItemKey :: Data.Text.Internal.Text
  -- | value: The metadata value
  , metadataItemValue :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON MetadataItem
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["key" Data.Aeson.Types.ToJSON..= metadataItemKey obj] : ["value" Data.Aeson.Types.ToJSON..= metadataItemValue obj] : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["key" Data.Aeson.Types.ToJSON..= metadataItemKey obj] : ["value" Data.Aeson.Types.ToJSON..= metadataItemValue obj] : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON MetadataItem
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "MetadataItem" (\obj -> (GHC.Base.pure MetadataItem GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "key")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "value"))
-- | Create a new 'MetadataItem' with all required fields.
mkMetadataItem :: Data.Text.Internal.Text -- ^ 'metadataItemKey'
  -> Data.Text.Internal.Text -- ^ 'metadataItemValue'
  -> MetadataItem
mkMetadataItem metadataItemKey metadataItemValue = MetadataItem{metadataItemKey = metadataItemKey,
                                                                metadataItemValue = metadataItemValue}
