-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema TrafficFilterRulesetRequest
module Model/Private/Elasticsearch.Types.TrafficFilterRulesetRequest where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Model/Private/Elasticsearch.Common
import Model/Private/Elasticsearch.TypeAlias
import {-# SOURCE #-} Model/Private/Elasticsearch.Types.TrafficFilterRule

-- | Defines the object schema located at @components.schemas.TrafficFilterRulesetRequest@ in the specification.
-- 
-- The specification for traffic filter ruleset.
data TrafficFilterRulesetRequest = TrafficFilterRulesetRequest {
  -- | description: Description of the ruleset
  trafficFilterRulesetRequestDescription :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | include_by_default: Should the ruleset be automatically included in the new deployments
  , trafficFilterRulesetRequestIncludeByDefault :: GHC.Types.Bool
  -- | name: Name of the ruleset
  , trafficFilterRulesetRequestName :: Data.Text.Internal.Text
  -- | region: The ruleset can be attached only to deployments in the specific region
  , trafficFilterRulesetRequestRegion :: Data.Text.Internal.Text
  -- | rules: List of rules
  , trafficFilterRulesetRequestRules :: ([TrafficFilterRule])
  -- | type: Type of the ruleset
  , trafficFilterRulesetRequestType :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON TrafficFilterRulesetRequest
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("description" Data.Aeson.Types.ToJSON..=)) (trafficFilterRulesetRequestDescription obj) : ["include_by_default" Data.Aeson.Types.ToJSON..= trafficFilterRulesetRequestIncludeByDefault obj] : ["name" Data.Aeson.Types.ToJSON..= trafficFilterRulesetRequestName obj] : ["region" Data.Aeson.Types.ToJSON..= trafficFilterRulesetRequestRegion obj] : ["rules" Data.Aeson.Types.ToJSON..= trafficFilterRulesetRequestRules obj] : ["type" Data.Aeson.Types.ToJSON..= trafficFilterRulesetRequestType obj] : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("description" Data.Aeson.Types.ToJSON..=)) (trafficFilterRulesetRequestDescription obj) : ["include_by_default" Data.Aeson.Types.ToJSON..= trafficFilterRulesetRequestIncludeByDefault obj] : ["name" Data.Aeson.Types.ToJSON..= trafficFilterRulesetRequestName obj] : ["region" Data.Aeson.Types.ToJSON..= trafficFilterRulesetRequestRegion obj] : ["rules" Data.Aeson.Types.ToJSON..= trafficFilterRulesetRequestRules obj] : ["type" Data.Aeson.Types.ToJSON..= trafficFilterRulesetRequestType obj] : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON TrafficFilterRulesetRequest
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "TrafficFilterRulesetRequest" (\obj -> (((((GHC.Base.pure TrafficFilterRulesetRequest GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "description")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "include_by_default")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "name")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "region")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "rules")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "type"))
-- | Create a new 'TrafficFilterRulesetRequest' with all required fields.
mkTrafficFilterRulesetRequest :: GHC.Types.Bool -- ^ 'trafficFilterRulesetRequestIncludeByDefault'
  -> Data.Text.Internal.Text -- ^ 'trafficFilterRulesetRequestName'
  -> Data.Text.Internal.Text -- ^ 'trafficFilterRulesetRequestRegion'
  -> [TrafficFilterRule] -- ^ 'trafficFilterRulesetRequestRules'
  -> Data.Text.Internal.Text -- ^ 'trafficFilterRulesetRequestType'
  -> TrafficFilterRulesetRequest
mkTrafficFilterRulesetRequest trafficFilterRulesetRequestIncludeByDefault trafficFilterRulesetRequestName trafficFilterRulesetRequestRegion trafficFilterRulesetRequestRules trafficFilterRulesetRequestType = TrafficFilterRulesetRequest{trafficFilterRulesetRequestDescription = GHC.Maybe.Nothing,
                                                                                                                                                                                                                                           trafficFilterRulesetRequestIncludeByDefault = trafficFilterRulesetRequestIncludeByDefault,
                                                                                                                                                                                                                                           trafficFilterRulesetRequestName = trafficFilterRulesetRequestName,
                                                                                                                                                                                                                                           trafficFilterRulesetRequestRegion = trafficFilterRulesetRequestRegion,
                                                                                                                                                                                                                                           trafficFilterRulesetRequestRules = trafficFilterRulesetRequestRules,
                                                                                                                                                                                                                                           trafficFilterRulesetRequestType = trafficFilterRulesetRequestType}
