module Model/Private/Elasticsearch.Types.TransientIntegrationsServerPlanConfiguration where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Model/Private/Elasticsearch.Common
data TransientIntegrationsServerPlanConfiguration
instance Show TransientIntegrationsServerPlanConfiguration
instance Eq TransientIntegrationsServerPlanConfiguration
instance FromJSON TransientIntegrationsServerPlanConfiguration
instance ToJSON TransientIntegrationsServerPlanConfiguration
