module Model/Private/Elasticsearch.Types.TransientAppSearchPlanConfiguration where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Model/Private/Elasticsearch.Common
data TransientAppSearchPlanConfiguration
instance Show TransientAppSearchPlanConfiguration
instance Eq TransientAppSearchPlanConfiguration
instance FromJSON TransientAppSearchPlanConfiguration
instance ToJSON TransientAppSearchPlanConfiguration
