-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the different functions to run the operation delete_organization_invitations
module Model/Private/Elasticsearch.Operations.Delete_organization_invitations where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Trans.Reader
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Either
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified Data.Vector
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Network.HTTP.Client
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Client as Network.HTTP.Client.Types
import qualified Network.HTTP.Simple
import qualified Network.HTTP.Types
import qualified Network.HTTP.Types as Network.HTTP.Types.Status
import qualified Network.HTTP.Types as Network.HTTP.Types.URI
import qualified Model/Private/Elasticsearch.Common
import Model/Private/Elasticsearch.Types

-- | > DELETE /organizations/{organization_id}/invitations/{invitation_tokens}
-- 
-- Deletes one or more organization invitations. Currently unavailable in self-hosted ECE.
delete_organization_invitations :: forall m . Model/Private/Elasticsearch.Common.MonadHTTP m => Delete_organization_invitationsParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> Model/Private/Elasticsearch.Common.ClientT m (Network.HTTP.Client.Types.Response Delete_organization_invitationsResponse) -- ^ Monadic computation which returns the result of the operation
delete_organization_invitations parameters = GHC.Base.fmap (\response_0 -> GHC.Base.fmap (Data.Either.either Delete_organization_invitationsResponseError GHC.Base.id GHC.Base.. (\response body -> if | (\status_1 -> Network.HTTP.Types.Status.statusCode status_1 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right Delete_organization_invitationsResponse200
                                                                                                                                                                                                       | (\status_2 -> Network.HTTP.Types.Status.statusCode status_2 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right Delete_organization_invitationsResponse400
                                                                                                                                                                                                       | (\status_3 -> Network.HTTP.Types.Status.statusCode status_3 GHC.Classes.== 404) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right Delete_organization_invitationsResponse404
                                                                                                                                                                                                       | GHC.Base.otherwise -> Data.Either.Left "Missing default response type") response_0) response_0) (Model/Private/Elasticsearch.Common.doCallWithConfigurationM (Data.Text.toUpper GHC.Base.$ Data.Text.pack "DELETE") (Data.Text.pack ("/organizations/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (delete_organization_invitationsParametersPathOrganization_id parameters))) GHC.Base.++ ("/invitations/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (delete_organization_invitationsParametersPathInvitation_tokens parameters))) GHC.Base.++ ""))))) GHC.Base.mempty)
-- | Defines the object schema located at @paths.\/organizations\/{organization_id}\/invitations\/{invitation_tokens}.DELETE.parameters@ in the specification.
-- 
-- 
data Delete_organization_invitationsParameters = Delete_organization_invitationsParameters {
  -- | pathInvitation_tokens: Represents the parameter named \'invitation_tokens\'
  -- 
  -- CSV list of Invitation tokens
  delete_organization_invitationsParametersPathInvitation_tokens :: Data.Text.Internal.Text
  -- | pathOrganization_id: Represents the parameter named \'organization_id\'
  -- 
  -- Identifier for the Organization
  , delete_organization_invitationsParametersPathOrganization_id :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Delete_organization_invitationsParameters
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["pathInvitation_tokens" Data.Aeson.Types.ToJSON..= delete_organization_invitationsParametersPathInvitation_tokens obj] : ["pathOrganization_id" Data.Aeson.Types.ToJSON..= delete_organization_invitationsParametersPathOrganization_id obj] : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["pathInvitation_tokens" Data.Aeson.Types.ToJSON..= delete_organization_invitationsParametersPathInvitation_tokens obj] : ["pathOrganization_id" Data.Aeson.Types.ToJSON..= delete_organization_invitationsParametersPathOrganization_id obj] : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON Delete_organization_invitationsParameters
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "Delete_organization_invitationsParameters" (\obj -> (GHC.Base.pure Delete_organization_invitationsParameters GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "pathInvitation_tokens")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "pathOrganization_id"))
-- | Create a new 'Delete_organization_invitationsParameters' with all required fields.
mkDelete_organization_invitationsParameters :: Data.Text.Internal.Text -- ^ 'delete_organization_invitationsParametersPathInvitation_tokens'
  -> Data.Text.Internal.Text -- ^ 'delete_organization_invitationsParametersPathOrganization_id'
  -> Delete_organization_invitationsParameters
mkDelete_organization_invitationsParameters delete_organization_invitationsParametersPathInvitation_tokens delete_organization_invitationsParametersPathOrganization_id = Delete_organization_invitationsParameters{delete_organization_invitationsParametersPathInvitation_tokens = delete_organization_invitationsParametersPathInvitation_tokens,
                                                                                                                                                                                                                    delete_organization_invitationsParametersPathOrganization_id = delete_organization_invitationsParametersPathOrganization_id}
-- | Represents a response of the operation 'delete_organization_invitations'.
-- 
-- The response constructor is chosen by the status code of the response. If no case matches (no specific case for the response code, no range case, no default case), 'Delete_organization_invitationsResponseError' is used.
data Delete_organization_invitationsResponse =
   Delete_organization_invitationsResponseError GHC.Base.String -- ^ Means either no matching case available or a parse error
  | Delete_organization_invitationsResponse200 -- ^ Organization invitations deleted successfully
  | Delete_organization_invitationsResponse400 -- ^ No valid invitation token was supplied. (code: \`root.invalid_data\`)
  | Delete_organization_invitationsResponse404 -- ^ * Organization not found. (code: \`organization.not_found\`) * Invitation not found. (code: \`organization.invitation_not_found\`)
  deriving (GHC.Show.Show, GHC.Classes.Eq)
-- | > DELETE /organizations/{organization_id}/invitations/{invitation_tokens}
-- 
-- The same as 'delete_organization_invitations' but accepts an explicit configuration.
delete_organization_invitationsWithConfiguration :: forall m . Model/Private/Elasticsearch.Common.MonadHTTP m => Model/Private/Elasticsearch.Common.Configuration -- ^ The configuration to use in the request
  -> Delete_organization_invitationsParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> m (Network.HTTP.Client.Types.Response Delete_organization_invitationsResponse) -- ^ Monadic computation which returns the result of the operation
delete_organization_invitationsWithConfiguration config
                                                 parameters = GHC.Base.fmap (\response_4 -> GHC.Base.fmap (Data.Either.either Delete_organization_invitationsResponseError GHC.Base.id GHC.Base.. (\response body -> if | (\status_5 -> Network.HTTP.Types.Status.statusCode status_5 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right Delete_organization_invitationsResponse200
                                                                                                                                                                                                                        | (\status_6 -> Network.HTTP.Types.Status.statusCode status_6 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right Delete_organization_invitationsResponse400
                                                                                                                                                                                                                        | (\status_7 -> Network.HTTP.Types.Status.statusCode status_7 GHC.Classes.== 404) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right Delete_organization_invitationsResponse404
                                                                                                                                                                                                                        | GHC.Base.otherwise -> Data.Either.Left "Missing default response type") response_4) response_4) (Model/Private/Elasticsearch.Common.doCallWithConfiguration config (Data.Text.toUpper GHC.Base.$ Data.Text.pack "DELETE") (Data.Text.pack ("/organizations/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (delete_organization_invitationsParametersPathOrganization_id parameters))) GHC.Base.++ ("/invitations/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (delete_organization_invitationsParametersPathInvitation_tokens parameters))) GHC.Base.++ ""))))) GHC.Base.mempty)
-- | > DELETE /organizations/{organization_id}/invitations/{invitation_tokens}
-- 
-- The same as 'delete_organization_invitations' but returns the raw 'Data.ByteString.Char8.ByteString'.
delete_organization_invitationsRaw :: forall m . Model/Private/Elasticsearch.Common.MonadHTTP m => Delete_organization_invitationsParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> Model/Private/Elasticsearch.Common.ClientT m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.ByteString) -- ^ Monadic computation which returns the result of the operation
delete_organization_invitationsRaw parameters = GHC.Base.id (Model/Private/Elasticsearch.Common.doCallWithConfigurationM (Data.Text.toUpper GHC.Base.$ Data.Text.pack "DELETE") (Data.Text.pack ("/organizations/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (delete_organization_invitationsParametersPathOrganization_id parameters))) GHC.Base.++ ("/invitations/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (delete_organization_invitationsParametersPathInvitation_tokens parameters))) GHC.Base.++ ""))))) GHC.Base.mempty)
-- | > DELETE /organizations/{organization_id}/invitations/{invitation_tokens}
-- 
-- The same as 'delete_organization_invitations' but accepts an explicit configuration and returns the raw 'Data.ByteString.Char8.ByteString'.
delete_organization_invitationsWithConfigurationRaw :: forall m . Model/Private/Elasticsearch.Common.MonadHTTP m => Model/Private/Elasticsearch.Common.Configuration -- ^ The configuration to use in the request
  -> Delete_organization_invitationsParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.ByteString) -- ^ Monadic computation which returns the result of the operation
delete_organization_invitationsWithConfigurationRaw config
                                                    parameters = GHC.Base.id (Model/Private/Elasticsearch.Common.doCallWithConfiguration config (Data.Text.toUpper GHC.Base.$ Data.Text.pack "DELETE") (Data.Text.pack ("/organizations/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (delete_organization_invitationsParametersPathOrganization_id parameters))) GHC.Base.++ ("/invitations/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (delete_organization_invitationsParametersPathInvitation_tokens parameters))) GHC.Base.++ ""))))) GHC.Base.mempty)
