-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the different functions to run the operation enable_deployment_resource_ccr
module Model/Private/Elasticsearch.Operations.Enable_deployment_resource_ccr where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Trans.Reader
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Either
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified Data.Vector
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Network.HTTP.Client
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Client as Network.HTTP.Client.Types
import qualified Network.HTTP.Simple
import qualified Network.HTTP.Types
import qualified Network.HTTP.Types as Network.HTTP.Types.Status
import qualified Network.HTTP.Types as Network.HTTP.Types.URI
import qualified Model/Private/Elasticsearch.Common
import Model/Private/Elasticsearch.Types

-- | > POST /deployments/{deployment_id}/elasticsearch/{ref_id}/_enable-ccr
-- 
-- Migrates the specified Elasticsearch resource and its associated Kibana to enable CCR (if supported).
enable_deployment_resource_ccr :: forall m . Model/Private/Elasticsearch.Common.MonadHTTP m => Enable_deployment_resource_ccrParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> Model/Private/Elasticsearch.Common.ClientT m (Network.HTTP.Client.Types.Response Enable_deployment_resource_ccrResponse) -- ^ Monadic computation which returns the result of the operation
enable_deployment_resource_ccr parameters = GHC.Base.fmap (\response_0 -> GHC.Base.fmap (Data.Either.either Enable_deployment_resource_ccrResponseError GHC.Base.id GHC.Base.. (\response body -> if | (\status_1 -> Network.HTTP.Types.Status.statusCode status_1 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right Enable_deployment_resource_ccrResponse200
                                                                                                                                                                                                     | (\status_2 -> Network.HTTP.Types.Status.statusCode status_2 GHC.Classes.== 404) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right Enable_deployment_resource_ccrResponse404
                                                                                                                                                                                                     | (\status_3 -> Network.HTTP.Types.Status.statusCode status_3 GHC.Classes.== 449) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right Enable_deployment_resource_ccrResponse449
                                                                                                                                                                                                     | GHC.Base.otherwise -> Data.Either.Left "Missing default response type") response_0) response_0) (Model/Private/Elasticsearch.Common.doCallWithConfigurationM (Data.Text.toUpper GHC.Base.$ Data.Text.pack "POST") (Data.Text.pack ("/deployments/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (enable_deployment_resource_ccrParametersPathDeployment_id parameters))) GHC.Base.++ ("/elasticsearch/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (enable_deployment_resource_ccrParametersPathRef_id parameters))) GHC.Base.++ "/_enable-ccr"))))) [Model/Private/Elasticsearch.Common.QueryParameter (Data.Text.pack "validate_only") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> enable_deployment_resource_ccrParametersQueryValidate_only parameters) (Data.Text.pack "form") GHC.Types.False])
-- | Defines the object schema located at @paths.\/deployments\/{deployment_id}\/elasticsearch\/{ref_id}\/_enable-ccr.POST.parameters@ in the specification.
-- 
-- 
data Enable_deployment_resource_ccrParameters = Enable_deployment_resource_ccrParameters {
  -- | pathDeployment_id: Represents the parameter named \'deployment_id\'
  -- 
  -- Identifier for the Deployment.
  enable_deployment_resource_ccrParametersPathDeployment_id :: Data.Text.Internal.Text
  -- | pathRef_id: Represents the parameter named \'ref_id\'
  -- 
  -- User-specified RefId for the Resource.
  , enable_deployment_resource_ccrParametersPathRef_id :: Data.Text.Internal.Text
  -- | queryValidate_only: Represents the parameter named \'validate_only\'
  -- 
  -- When \`true\`, will not enable CCR but returns warnings if any elements may lose availability during CCR enablement
  , enable_deployment_resource_ccrParametersQueryValidate_only :: (GHC.Maybe.Maybe GHC.Types.Bool)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Enable_deployment_resource_ccrParameters
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["pathDeployment_id" Data.Aeson.Types.ToJSON..= enable_deployment_resource_ccrParametersPathDeployment_id obj] : ["pathRef_id" Data.Aeson.Types.ToJSON..= enable_deployment_resource_ccrParametersPathRef_id obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("queryValidate_only" Data.Aeson.Types.ToJSON..=)) (enable_deployment_resource_ccrParametersQueryValidate_only obj) : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["pathDeployment_id" Data.Aeson.Types.ToJSON..= enable_deployment_resource_ccrParametersPathDeployment_id obj] : ["pathRef_id" Data.Aeson.Types.ToJSON..= enable_deployment_resource_ccrParametersPathRef_id obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("queryValidate_only" Data.Aeson.Types.ToJSON..=)) (enable_deployment_resource_ccrParametersQueryValidate_only obj) : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON Enable_deployment_resource_ccrParameters
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "Enable_deployment_resource_ccrParameters" (\obj -> ((GHC.Base.pure Enable_deployment_resource_ccrParameters GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "pathDeployment_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "pathRef_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "queryValidate_only"))
-- | Create a new 'Enable_deployment_resource_ccrParameters' with all required fields.
mkEnable_deployment_resource_ccrParameters :: Data.Text.Internal.Text -- ^ 'enable_deployment_resource_ccrParametersPathDeployment_id'
  -> Data.Text.Internal.Text -- ^ 'enable_deployment_resource_ccrParametersPathRef_id'
  -> Enable_deployment_resource_ccrParameters
mkEnable_deployment_resource_ccrParameters enable_deployment_resource_ccrParametersPathDeployment_id enable_deployment_resource_ccrParametersPathRef_id = Enable_deployment_resource_ccrParameters{enable_deployment_resource_ccrParametersPathDeployment_id = enable_deployment_resource_ccrParametersPathDeployment_id,
                                                                                                                                                                                                   enable_deployment_resource_ccrParametersPathRef_id = enable_deployment_resource_ccrParametersPathRef_id,
                                                                                                                                                                                                   enable_deployment_resource_ccrParametersQueryValidate_only = GHC.Maybe.Nothing}
-- | Represents a response of the operation 'enable_deployment_resource_ccr'.
-- 
-- The response constructor is chosen by the status code of the response. If no case matches (no specific case for the response code, no range case, no default case), 'Enable_deployment_resource_ccrResponseError' is used.
data Enable_deployment_resource_ccrResponse =
   Enable_deployment_resource_ccrResponseError GHC.Base.String -- ^ Means either no matching case available or a parse error
  | Enable_deployment_resource_ccrResponse200 -- ^ Standard response
  | Enable_deployment_resource_ccrResponse404 -- ^ * The Deployment specified by {deployment_id} cannot be found. (code: \`deployments.deployment_not_found\`) * The Resource specified by {ref_id} cannot be found. (code: \`deployments.deployment_resource_not_found\`)
  | Enable_deployment_resource_ccrResponse449 -- ^ Elevated permissions are required. (code: \`root.unauthorized.rbac.elevated_permissions_required\`)
  deriving (GHC.Show.Show, GHC.Classes.Eq)
-- | > POST /deployments/{deployment_id}/elasticsearch/{ref_id}/_enable-ccr
-- 
-- The same as 'enable_deployment_resource_ccr' but accepts an explicit configuration.
enable_deployment_resource_ccrWithConfiguration :: forall m . Model/Private/Elasticsearch.Common.MonadHTTP m => Model/Private/Elasticsearch.Common.Configuration -- ^ The configuration to use in the request
  -> Enable_deployment_resource_ccrParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> m (Network.HTTP.Client.Types.Response Enable_deployment_resource_ccrResponse) -- ^ Monadic computation which returns the result of the operation
enable_deployment_resource_ccrWithConfiguration config
                                                parameters = GHC.Base.fmap (\response_4 -> GHC.Base.fmap (Data.Either.either Enable_deployment_resource_ccrResponseError GHC.Base.id GHC.Base.. (\response body -> if | (\status_5 -> Network.HTTP.Types.Status.statusCode status_5 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right Enable_deployment_resource_ccrResponse200
                                                                                                                                                                                                                      | (\status_6 -> Network.HTTP.Types.Status.statusCode status_6 GHC.Classes.== 404) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right Enable_deployment_resource_ccrResponse404
                                                                                                                                                                                                                      | (\status_7 -> Network.HTTP.Types.Status.statusCode status_7 GHC.Classes.== 449) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right Enable_deployment_resource_ccrResponse449
                                                                                                                                                                                                                      | GHC.Base.otherwise -> Data.Either.Left "Missing default response type") response_4) response_4) (Model/Private/Elasticsearch.Common.doCallWithConfiguration config (Data.Text.toUpper GHC.Base.$ Data.Text.pack "POST") (Data.Text.pack ("/deployments/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (enable_deployment_resource_ccrParametersPathDeployment_id parameters))) GHC.Base.++ ("/elasticsearch/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (enable_deployment_resource_ccrParametersPathRef_id parameters))) GHC.Base.++ "/_enable-ccr"))))) [Model/Private/Elasticsearch.Common.QueryParameter (Data.Text.pack "validate_only") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> enable_deployment_resource_ccrParametersQueryValidate_only parameters) (Data.Text.pack "form") GHC.Types.False])
-- | > POST /deployments/{deployment_id}/elasticsearch/{ref_id}/_enable-ccr
-- 
-- The same as 'enable_deployment_resource_ccr' but returns the raw 'Data.ByteString.Char8.ByteString'.
enable_deployment_resource_ccrRaw :: forall m . Model/Private/Elasticsearch.Common.MonadHTTP m => Enable_deployment_resource_ccrParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> Model/Private/Elasticsearch.Common.ClientT m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.ByteString) -- ^ Monadic computation which returns the result of the operation
enable_deployment_resource_ccrRaw parameters = GHC.Base.id (Model/Private/Elasticsearch.Common.doCallWithConfigurationM (Data.Text.toUpper GHC.Base.$ Data.Text.pack "POST") (Data.Text.pack ("/deployments/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (enable_deployment_resource_ccrParametersPathDeployment_id parameters))) GHC.Base.++ ("/elasticsearch/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (enable_deployment_resource_ccrParametersPathRef_id parameters))) GHC.Base.++ "/_enable-ccr"))))) [Model/Private/Elasticsearch.Common.QueryParameter (Data.Text.pack "validate_only") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> enable_deployment_resource_ccrParametersQueryValidate_only parameters) (Data.Text.pack "form") GHC.Types.False])
-- | > POST /deployments/{deployment_id}/elasticsearch/{ref_id}/_enable-ccr
-- 
-- The same as 'enable_deployment_resource_ccr' but accepts an explicit configuration and returns the raw 'Data.ByteString.Char8.ByteString'.
enable_deployment_resource_ccrWithConfigurationRaw :: forall m . Model/Private/Elasticsearch.Common.MonadHTTP m => Model/Private/Elasticsearch.Common.Configuration -- ^ The configuration to use in the request
  -> Enable_deployment_resource_ccrParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.ByteString) -- ^ Monadic computation which returns the result of the operation
enable_deployment_resource_ccrWithConfigurationRaw config
                                                   parameters = GHC.Base.id (Model/Private/Elasticsearch.Common.doCallWithConfiguration config (Data.Text.toUpper GHC.Base.$ Data.Text.pack "POST") (Data.Text.pack ("/deployments/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (enable_deployment_resource_ccrParametersPathDeployment_id parameters))) GHC.Base.++ ("/elasticsearch/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (enable_deployment_resource_ccrParametersPathRef_id parameters))) GHC.Base.++ "/_enable-ccr"))))) [Model/Private/Elasticsearch.Common.QueryParameter (Data.Text.pack "validate_only") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> enable_deployment_resource_ccrParametersQueryValidate_only parameters) (Data.Text.pack "form") GHC.Types.False])
