-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the different functions to run the operation upgrade_deployment_stateless_resource
module Model/Private/Elasticsearch.Operations.Upgrade_deployment_stateless_resource where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Trans.Reader
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Either
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified Data.Vector
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Network.HTTP.Client
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Client as Network.HTTP.Client.Types
import qualified Network.HTTP.Simple
import qualified Network.HTTP.Types
import qualified Network.HTTP.Types as Network.HTTP.Types.Status
import qualified Network.HTTP.Types as Network.HTTP.Types.URI
import qualified Model/Private/Elasticsearch.Common
import Model/Private/Elasticsearch.Types

-- | > POST /deployments/{deployment_id}/{stateless_resource_kind}/{ref_id}/_upgrade
-- 
-- Upgrades a running cluster.
upgrade_deployment_stateless_resource :: forall m . Model/Private/Elasticsearch.Common.MonadHTTP m => Upgrade_deployment_stateless_resourceParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> Model/Private/Elasticsearch.Common.ClientT m (Network.HTTP.Client.Types.Response Upgrade_deployment_stateless_resourceResponse) -- ^ Monadic computation which returns the result of the operation
upgrade_deployment_stateless_resource parameters = GHC.Base.fmap (\response_0 -> GHC.Base.fmap (Data.Either.either Upgrade_deployment_stateless_resourceResponseError GHC.Base.id GHC.Base.. (\response body -> if | (\status_1 -> Network.HTTP.Types.Status.statusCode status_1 GHC.Classes.== 202) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right Upgrade_deployment_stateless_resourceResponse202
                                                                                                                                                                                                                   | (\status_2 -> Network.HTTP.Types.Status.statusCode status_2 GHC.Classes.== 404) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right Upgrade_deployment_stateless_resourceResponse404
                                                                                                                                                                                                                   | (\status_3 -> Network.HTTP.Types.Status.statusCode status_3 GHC.Classes.== 449) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right Upgrade_deployment_stateless_resourceResponse449
                                                                                                                                                                                                                   | GHC.Base.otherwise -> Data.Either.Left "Missing default response type") response_0) response_0) (Model/Private/Elasticsearch.Common.doCallWithConfigurationM (Data.Text.toUpper GHC.Base.$ Data.Text.pack "POST") (Data.Text.pack ("/deployments/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (upgrade_deployment_stateless_resourceParametersPathDeployment_id parameters))) GHC.Base.++ ("/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (upgrade_deployment_stateless_resourceParametersPathStateless_resource_kind parameters))) GHC.Base.++ ("/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (upgrade_deployment_stateless_resourceParametersPathRef_id parameters))) GHC.Base.++ "/_upgrade"))))))) [Model/Private/Elasticsearch.Common.QueryParameter (Data.Text.pack "validate_only") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> upgrade_deployment_stateless_resourceParametersQueryValidate_only parameters) (Data.Text.pack "form") GHC.Types.False])
-- | Defines the object schema located at @paths.\/deployments\/{deployment_id}\/{stateless_resource_kind}\/{ref_id}\/_upgrade.POST.parameters@ in the specification.
-- 
-- 
data Upgrade_deployment_stateless_resourceParameters = Upgrade_deployment_stateless_resourceParameters {
  -- | pathDeployment_id: Represents the parameter named \'deployment_id\'
  -- 
  -- Identifier for the Deployment.
  upgrade_deployment_stateless_resourceParametersPathDeployment_id :: Data.Text.Internal.Text
  -- | pathRef_id: Represents the parameter named \'ref_id\'
  -- 
  -- User-specified RefId for the Resource.
  , upgrade_deployment_stateless_resourceParametersPathRef_id :: Data.Text.Internal.Text
  -- | pathStateless_resource_kind: Represents the parameter named \'stateless_resource_kind\'
  -- 
  -- The kind of stateless resource
  , upgrade_deployment_stateless_resourceParametersPathStateless_resource_kind :: Upgrade_deployment_stateless_resourceParametersPathStateless_resource_kind
  -- | queryValidate_only: Represents the parameter named \'validate_only\'
  -- 
  -- When \`true\`, returns the update version without performing the upgrade
  , upgrade_deployment_stateless_resourceParametersQueryValidate_only :: (GHC.Maybe.Maybe GHC.Types.Bool)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Upgrade_deployment_stateless_resourceParameters
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["pathDeployment_id" Data.Aeson.Types.ToJSON..= upgrade_deployment_stateless_resourceParametersPathDeployment_id obj] : ["pathRef_id" Data.Aeson.Types.ToJSON..= upgrade_deployment_stateless_resourceParametersPathRef_id obj] : ["pathStateless_resource_kind" Data.Aeson.Types.ToJSON..= upgrade_deployment_stateless_resourceParametersPathStateless_resource_kind obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("queryValidate_only" Data.Aeson.Types.ToJSON..=)) (upgrade_deployment_stateless_resourceParametersQueryValidate_only obj) : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["pathDeployment_id" Data.Aeson.Types.ToJSON..= upgrade_deployment_stateless_resourceParametersPathDeployment_id obj] : ["pathRef_id" Data.Aeson.Types.ToJSON..= upgrade_deployment_stateless_resourceParametersPathRef_id obj] : ["pathStateless_resource_kind" Data.Aeson.Types.ToJSON..= upgrade_deployment_stateless_resourceParametersPathStateless_resource_kind obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("queryValidate_only" Data.Aeson.Types.ToJSON..=)) (upgrade_deployment_stateless_resourceParametersQueryValidate_only obj) : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON Upgrade_deployment_stateless_resourceParameters
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "Upgrade_deployment_stateless_resourceParameters" (\obj -> (((GHC.Base.pure Upgrade_deployment_stateless_resourceParameters GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "pathDeployment_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "pathRef_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "pathStateless_resource_kind")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "queryValidate_only"))
-- | Create a new 'Upgrade_deployment_stateless_resourceParameters' with all required fields.
mkUpgrade_deployment_stateless_resourceParameters :: Data.Text.Internal.Text -- ^ 'upgrade_deployment_stateless_resourceParametersPathDeployment_id'
  -> Data.Text.Internal.Text -- ^ 'upgrade_deployment_stateless_resourceParametersPathRef_id'
  -> Upgrade_deployment_stateless_resourceParametersPathStateless_resource_kind -- ^ 'upgrade_deployment_stateless_resourceParametersPathStateless_resource_kind'
  -> Upgrade_deployment_stateless_resourceParameters
mkUpgrade_deployment_stateless_resourceParameters upgrade_deployment_stateless_resourceParametersPathDeployment_id upgrade_deployment_stateless_resourceParametersPathRef_id upgrade_deployment_stateless_resourceParametersPathStateless_resource_kind = Upgrade_deployment_stateless_resourceParameters{upgrade_deployment_stateless_resourceParametersPathDeployment_id = upgrade_deployment_stateless_resourceParametersPathDeployment_id,
                                                                                                                                                                                                                                                                                                          upgrade_deployment_stateless_resourceParametersPathRef_id = upgrade_deployment_stateless_resourceParametersPathRef_id,
                                                                                                                                                                                                                                                                                                          upgrade_deployment_stateless_resourceParametersPathStateless_resource_kind = upgrade_deployment_stateless_resourceParametersPathStateless_resource_kind,
                                                                                                                                                                                                                                                                                                          upgrade_deployment_stateless_resourceParametersQueryValidate_only = GHC.Maybe.Nothing}
-- | Defines the enum schema located at @paths.\/deployments\/{deployment_id}\/{stateless_resource_kind}\/{ref_id}\/_upgrade.POST.parameters.properties.pathStateless_resource_kind@ in the specification.
-- 
-- Represents the parameter named \'stateless_resource_kind\'
-- 
-- The kind of stateless resource
data Upgrade_deployment_stateless_resourceParametersPathStateless_resource_kind =
   Upgrade_deployment_stateless_resourceParametersPathStateless_resource_kindOther Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | Upgrade_deployment_stateless_resourceParametersPathStateless_resource_kindTyped Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | Upgrade_deployment_stateless_resourceParametersPathStateless_resource_kindEnumKibana -- ^ Represents the JSON value @"kibana"@
  | Upgrade_deployment_stateless_resourceParametersPathStateless_resource_kindEnumApm -- ^ Represents the JSON value @"apm"@
  | Upgrade_deployment_stateless_resourceParametersPathStateless_resource_kindEnumAppsearch -- ^ Represents the JSON value @"appsearch"@
  | Upgrade_deployment_stateless_resourceParametersPathStateless_resource_kindEnumEnterprise_search -- ^ Represents the JSON value @"enterprise_search"@
  | Upgrade_deployment_stateless_resourceParametersPathStateless_resource_kindEnumIntegrations_server -- ^ Represents the JSON value @"integrations_server"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Upgrade_deployment_stateless_resourceParametersPathStateless_resource_kind
    where toJSON (Upgrade_deployment_stateless_resourceParametersPathStateless_resource_kindOther val) = val
          toJSON (Upgrade_deployment_stateless_resourceParametersPathStateless_resource_kindTyped val) = Data.Aeson.Types.ToJSON.toJSON val
          toJSON (Upgrade_deployment_stateless_resourceParametersPathStateless_resource_kindEnumKibana) = "kibana"
          toJSON (Upgrade_deployment_stateless_resourceParametersPathStateless_resource_kindEnumApm) = "apm"
          toJSON (Upgrade_deployment_stateless_resourceParametersPathStateless_resource_kindEnumAppsearch) = "appsearch"
          toJSON (Upgrade_deployment_stateless_resourceParametersPathStateless_resource_kindEnumEnterprise_search) = "enterprise_search"
          toJSON (Upgrade_deployment_stateless_resourceParametersPathStateless_resource_kindEnumIntegrations_server) = "integrations_server"
instance Data.Aeson.Types.FromJSON.FromJSON Upgrade_deployment_stateless_resourceParametersPathStateless_resource_kind
    where parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "kibana" -> Upgrade_deployment_stateless_resourceParametersPathStateless_resource_kindEnumKibana
                                            | val GHC.Classes.== "apm" -> Upgrade_deployment_stateless_resourceParametersPathStateless_resource_kindEnumApm
                                            | val GHC.Classes.== "appsearch" -> Upgrade_deployment_stateless_resourceParametersPathStateless_resource_kindEnumAppsearch
                                            | val GHC.Classes.== "enterprise_search" -> Upgrade_deployment_stateless_resourceParametersPathStateless_resource_kindEnumEnterprise_search
                                            | val GHC.Classes.== "integrations_server" -> Upgrade_deployment_stateless_resourceParametersPathStateless_resource_kindEnumIntegrations_server
                                            | GHC.Base.otherwise -> Upgrade_deployment_stateless_resourceParametersPathStateless_resource_kindOther val)
-- | Represents a response of the operation 'upgrade_deployment_stateless_resource'.
-- 
-- The response constructor is chosen by the status code of the response. If no case matches (no specific case for the response code, no range case, no default case), 'Upgrade_deployment_stateless_resourceResponseError' is used.
data Upgrade_deployment_stateless_resourceResponse =
   Upgrade_deployment_stateless_resourceResponseError GHC.Base.String -- ^ Means either no matching case available or a parse error
  | Upgrade_deployment_stateless_resourceResponse202 -- ^ The upgrade command was issued successfully. Use the \"GET\" command on the \/{deployment_id} resource to monitor progress
  | Upgrade_deployment_stateless_resourceResponse404 -- ^ * The Deployment specified by {deployment_id} cannot be found. (code: \`deployments.deployment_not_found\`) * The Resource specified by {ref_id} cannot be found. (code: \`deployments.deployment_resource_not_found\`)
  | Upgrade_deployment_stateless_resourceResponse449 -- ^ Elevated permissions are required. (code: \`root.unauthorized.rbac.elevated_permissions_required\`)
  deriving (GHC.Show.Show, GHC.Classes.Eq)
-- | > POST /deployments/{deployment_id}/{stateless_resource_kind}/{ref_id}/_upgrade
-- 
-- The same as 'upgrade_deployment_stateless_resource' but accepts an explicit configuration.
upgrade_deployment_stateless_resourceWithConfiguration :: forall m . Model/Private/Elasticsearch.Common.MonadHTTP m => Model/Private/Elasticsearch.Common.Configuration -- ^ The configuration to use in the request
  -> Upgrade_deployment_stateless_resourceParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> m (Network.HTTP.Client.Types.Response Upgrade_deployment_stateless_resourceResponse) -- ^ Monadic computation which returns the result of the operation
upgrade_deployment_stateless_resourceWithConfiguration config
                                                       parameters = GHC.Base.fmap (\response_4 -> GHC.Base.fmap (Data.Either.either Upgrade_deployment_stateless_resourceResponseError GHC.Base.id GHC.Base.. (\response body -> if | (\status_5 -> Network.HTTP.Types.Status.statusCode status_5 GHC.Classes.== 202) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right Upgrade_deployment_stateless_resourceResponse202
                                                                                                                                                                                                                                    | (\status_6 -> Network.HTTP.Types.Status.statusCode status_6 GHC.Classes.== 404) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right Upgrade_deployment_stateless_resourceResponse404
                                                                                                                                                                                                                                    | (\status_7 -> Network.HTTP.Types.Status.statusCode status_7 GHC.Classes.== 449) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right Upgrade_deployment_stateless_resourceResponse449
                                                                                                                                                                                                                                    | GHC.Base.otherwise -> Data.Either.Left "Missing default response type") response_4) response_4) (Model/Private/Elasticsearch.Common.doCallWithConfiguration config (Data.Text.toUpper GHC.Base.$ Data.Text.pack "POST") (Data.Text.pack ("/deployments/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (upgrade_deployment_stateless_resourceParametersPathDeployment_id parameters))) GHC.Base.++ ("/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (upgrade_deployment_stateless_resourceParametersPathStateless_resource_kind parameters))) GHC.Base.++ ("/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (upgrade_deployment_stateless_resourceParametersPathRef_id parameters))) GHC.Base.++ "/_upgrade"))))))) [Model/Private/Elasticsearch.Common.QueryParameter (Data.Text.pack "validate_only") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> upgrade_deployment_stateless_resourceParametersQueryValidate_only parameters) (Data.Text.pack "form") GHC.Types.False])
-- | > POST /deployments/{deployment_id}/{stateless_resource_kind}/{ref_id}/_upgrade
-- 
-- The same as 'upgrade_deployment_stateless_resource' but returns the raw 'Data.ByteString.Char8.ByteString'.
upgrade_deployment_stateless_resourceRaw :: forall m . Model/Private/Elasticsearch.Common.MonadHTTP m => Upgrade_deployment_stateless_resourceParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> Model/Private/Elasticsearch.Common.ClientT m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.ByteString) -- ^ Monadic computation which returns the result of the operation
upgrade_deployment_stateless_resourceRaw parameters = GHC.Base.id (Model/Private/Elasticsearch.Common.doCallWithConfigurationM (Data.Text.toUpper GHC.Base.$ Data.Text.pack "POST") (Data.Text.pack ("/deployments/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (upgrade_deployment_stateless_resourceParametersPathDeployment_id parameters))) GHC.Base.++ ("/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (upgrade_deployment_stateless_resourceParametersPathStateless_resource_kind parameters))) GHC.Base.++ ("/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (upgrade_deployment_stateless_resourceParametersPathRef_id parameters))) GHC.Base.++ "/_upgrade"))))))) [Model/Private/Elasticsearch.Common.QueryParameter (Data.Text.pack "validate_only") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> upgrade_deployment_stateless_resourceParametersQueryValidate_only parameters) (Data.Text.pack "form") GHC.Types.False])
-- | > POST /deployments/{deployment_id}/{stateless_resource_kind}/{ref_id}/_upgrade
-- 
-- The same as 'upgrade_deployment_stateless_resource' but accepts an explicit configuration and returns the raw 'Data.ByteString.Char8.ByteString'.
upgrade_deployment_stateless_resourceWithConfigurationRaw :: forall m . Model/Private/Elasticsearch.Common.MonadHTTP m => Model/Private/Elasticsearch.Common.Configuration -- ^ The configuration to use in the request
  -> Upgrade_deployment_stateless_resourceParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.ByteString) -- ^ Monadic computation which returns the result of the operation
upgrade_deployment_stateless_resourceWithConfigurationRaw config
                                                          parameters = GHC.Base.id (Model/Private/Elasticsearch.Common.doCallWithConfiguration config (Data.Text.toUpper GHC.Base.$ Data.Text.pack "POST") (Data.Text.pack ("/deployments/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (upgrade_deployment_stateless_resourceParametersPathDeployment_id parameters))) GHC.Base.++ ("/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (upgrade_deployment_stateless_resourceParametersPathStateless_resource_kind parameters))) GHC.Base.++ ("/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (upgrade_deployment_stateless_resourceParametersPathRef_id parameters))) GHC.Base.++ "/_upgrade"))))))) [Model/Private/Elasticsearch.Common.QueryParameter (Data.Text.pack "validate_only") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> upgrade_deployment_stateless_resourceParametersQueryValidate_only parameters) (Data.Text.pack "form") GHC.Types.False])
