-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the different functions to run the operation upgradeDeploymentStatelessResource
module Model/Private/Elasticsearch.Operations.UpgradeDeploymentStatelessResource where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Trans.Reader
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Either
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified Data.Vector
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Network.HTTP.Client
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Client as Network.HTTP.Client.Types
import qualified Network.HTTP.Simple
import qualified Network.HTTP.Types
import qualified Network.HTTP.Types as Network.HTTP.Types.Status
import qualified Network.HTTP.Types as Network.HTTP.Types.URI
import qualified Model/Private/Elasticsearch.Common
import Model/Private/Elasticsearch.Types

-- | > POST /deployments/{deployment_id}/{stateless_resource_kind}/{ref_id}/_upgrade
-- 
-- Upgrades a running cluster.
upgradeDeploymentStatelessResource :: forall m . Model/Private/Elasticsearch.Common.MonadHTTP m => UpgradeDeploymentStatelessResourceParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> Model/Private/Elasticsearch.Common.ClientT m (Network.HTTP.Client.Types.Response UpgradeDeploymentStatelessResourceResponse) -- ^ Monadic computation which returns the result of the operation
upgradeDeploymentStatelessResource parameters = GHC.Base.fmap (\response_0 -> GHC.Base.fmap (Data.Either.either UpgradeDeploymentStatelessResourceResponseError GHC.Base.id GHC.Base.. (\response body -> if | (\status_1 -> Network.HTTP.Types.Status.statusCode status_1 GHC.Classes.== 202) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right UpgradeDeploymentStatelessResourceResponse202
                                                                                                                                                                                                             | (\status_2 -> Network.HTTP.Types.Status.statusCode status_2 GHC.Classes.== 404) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right UpgradeDeploymentStatelessResourceResponse404
                                                                                                                                                                                                             | (\status_3 -> Network.HTTP.Types.Status.statusCode status_3 GHC.Classes.== 449) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right UpgradeDeploymentStatelessResourceResponse449
                                                                                                                                                                                                             | GHC.Base.otherwise -> Data.Either.Left "Missing default response type") response_0) response_0) (Model/Private/Elasticsearch.Common.doCallWithConfigurationM (Data.Text.toUpper GHC.Base.$ Data.Text.pack "POST") (Data.Text.pack ("/deployments/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (upgradeDeploymentStatelessResourceParametersPathDeploymentId parameters))) GHC.Base.++ ("/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (upgradeDeploymentStatelessResourceParametersPathStatelessResourceKind parameters))) GHC.Base.++ ("/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (upgradeDeploymentStatelessResourceParametersPathRefId parameters))) GHC.Base.++ "/_upgrade"))))))) [Model/Private/Elasticsearch.Common.QueryParameter (Data.Text.pack "validate_only") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> upgradeDeploymentStatelessResourceParametersQueryValidateOnly parameters) (Data.Text.pack "form") GHC.Types.False])
-- | Defines the object schema located at @paths.\/deployments\/{deployment_id}\/{stateless_resource_kind}\/{ref_id}\/_upgrade.POST.parameters@ in the specification.
-- 
-- 
data UpgradeDeploymentStatelessResourceParameters = UpgradeDeploymentStatelessResourceParameters {
  -- | pathDeployment_id: Represents the parameter named \'deployment_id\'
  -- 
  -- Identifier for the Deployment.
  upgradeDeploymentStatelessResourceParametersPathDeploymentId :: Data.Text.Internal.Text
  -- | pathRef_id: Represents the parameter named \'ref_id\'
  -- 
  -- User-specified RefId for the Resource.
  , upgradeDeploymentStatelessResourceParametersPathRefId :: Data.Text.Internal.Text
  -- | pathStateless_resource_kind: Represents the parameter named \'stateless_resource_kind\'
  -- 
  -- The kind of stateless resource
  , upgradeDeploymentStatelessResourceParametersPathStatelessResourceKind :: UpgradeDeploymentStatelessResourceParametersPathStatelessResourceKind
  -- | queryValidate_only: Represents the parameter named \'validate_only\'
  -- 
  -- When \`true\`, returns the update version without performing the upgrade
  , upgradeDeploymentStatelessResourceParametersQueryValidateOnly :: (GHC.Maybe.Maybe GHC.Types.Bool)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON UpgradeDeploymentStatelessResourceParameters
    where toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["pathDeployment_id" Data.Aeson.Types.ToJSON..= upgradeDeploymentStatelessResourceParametersPathDeploymentId obj] : ["pathRef_id" Data.Aeson.Types.ToJSON..= upgradeDeploymentStatelessResourceParametersPathRefId obj] : ["pathStateless_resource_kind" Data.Aeson.Types.ToJSON..= upgradeDeploymentStatelessResourceParametersPathStatelessResourceKind obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("queryValidate_only" Data.Aeson.Types.ToJSON..=)) (upgradeDeploymentStatelessResourceParametersQueryValidateOnly obj) : GHC.Base.mempty))
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["pathDeployment_id" Data.Aeson.Types.ToJSON..= upgradeDeploymentStatelessResourceParametersPathDeploymentId obj] : ["pathRef_id" Data.Aeson.Types.ToJSON..= upgradeDeploymentStatelessResourceParametersPathRefId obj] : ["pathStateless_resource_kind" Data.Aeson.Types.ToJSON..= upgradeDeploymentStatelessResourceParametersPathStatelessResourceKind obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("queryValidate_only" Data.Aeson.Types.ToJSON..=)) (upgradeDeploymentStatelessResourceParametersQueryValidateOnly obj) : GHC.Base.mempty)))
instance Data.Aeson.Types.FromJSON.FromJSON UpgradeDeploymentStatelessResourceParameters
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "UpgradeDeploymentStatelessResourceParameters" (\obj -> (((GHC.Base.pure UpgradeDeploymentStatelessResourceParameters GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "pathDeployment_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "pathRef_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "pathStateless_resource_kind")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "queryValidate_only"))
-- | Create a new 'UpgradeDeploymentStatelessResourceParameters' with all required fields.
mkUpgradeDeploymentStatelessResourceParameters :: Data.Text.Internal.Text -- ^ 'upgradeDeploymentStatelessResourceParametersPathDeploymentId'
  -> Data.Text.Internal.Text -- ^ 'upgradeDeploymentStatelessResourceParametersPathRefId'
  -> UpgradeDeploymentStatelessResourceParametersPathStatelessResourceKind -- ^ 'upgradeDeploymentStatelessResourceParametersPathStatelessResourceKind'
  -> UpgradeDeploymentStatelessResourceParameters
mkUpgradeDeploymentStatelessResourceParameters upgradeDeploymentStatelessResourceParametersPathDeploymentId upgradeDeploymentStatelessResourceParametersPathRefId upgradeDeploymentStatelessResourceParametersPathStatelessResourceKind = UpgradeDeploymentStatelessResourceParameters{upgradeDeploymentStatelessResourceParametersPathDeploymentId = upgradeDeploymentStatelessResourceParametersPathDeploymentId,
                                                                                                                                                                                                                                                                                       upgradeDeploymentStatelessResourceParametersPathRefId = upgradeDeploymentStatelessResourceParametersPathRefId,
                                                                                                                                                                                                                                                                                       upgradeDeploymentStatelessResourceParametersPathStatelessResourceKind = upgradeDeploymentStatelessResourceParametersPathStatelessResourceKind,
                                                                                                                                                                                                                                                                                       upgradeDeploymentStatelessResourceParametersQueryValidateOnly = GHC.Maybe.Nothing}
-- | Defines the enum schema located at @paths.\/deployments\/{deployment_id}\/{stateless_resource_kind}\/{ref_id}\/_upgrade.POST.parameters.properties.pathStateless_resource_kind@ in the specification.
-- 
-- Represents the parameter named \'stateless_resource_kind\'
-- 
-- The kind of stateless resource
data UpgradeDeploymentStatelessResourceParametersPathStatelessResourceKind =
   UpgradeDeploymentStatelessResourceParametersPathStatelessResourceKindOther Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | UpgradeDeploymentStatelessResourceParametersPathStatelessResourceKindTyped Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | UpgradeDeploymentStatelessResourceParametersPathStatelessResourceKindEnumKibana -- ^ Represents the JSON value @"kibana"@
  | UpgradeDeploymentStatelessResourceParametersPathStatelessResourceKindEnumApm -- ^ Represents the JSON value @"apm"@
  | UpgradeDeploymentStatelessResourceParametersPathStatelessResourceKindEnumAppsearch -- ^ Represents the JSON value @"appsearch"@
  | UpgradeDeploymentStatelessResourceParametersPathStatelessResourceKindEnumEnterpriseSearch -- ^ Represents the JSON value @"enterprise_search"@
  | UpgradeDeploymentStatelessResourceParametersPathStatelessResourceKindEnumIntegrationsServer -- ^ Represents the JSON value @"integrations_server"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON UpgradeDeploymentStatelessResourceParametersPathStatelessResourceKind
    where toJSON (UpgradeDeploymentStatelessResourceParametersPathStatelessResourceKindOther val) = val
          toJSON (UpgradeDeploymentStatelessResourceParametersPathStatelessResourceKindTyped val) = Data.Aeson.Types.ToJSON.toJSON val
          toJSON (UpgradeDeploymentStatelessResourceParametersPathStatelessResourceKindEnumKibana) = "kibana"
          toJSON (UpgradeDeploymentStatelessResourceParametersPathStatelessResourceKindEnumApm) = "apm"
          toJSON (UpgradeDeploymentStatelessResourceParametersPathStatelessResourceKindEnumAppsearch) = "appsearch"
          toJSON (UpgradeDeploymentStatelessResourceParametersPathStatelessResourceKindEnumEnterpriseSearch) = "enterprise_search"
          toJSON (UpgradeDeploymentStatelessResourceParametersPathStatelessResourceKindEnumIntegrationsServer) = "integrations_server"
instance Data.Aeson.Types.FromJSON.FromJSON UpgradeDeploymentStatelessResourceParametersPathStatelessResourceKind
    where parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "kibana" -> UpgradeDeploymentStatelessResourceParametersPathStatelessResourceKindEnumKibana
                                            | val GHC.Classes.== "apm" -> UpgradeDeploymentStatelessResourceParametersPathStatelessResourceKindEnumApm
                                            | val GHC.Classes.== "appsearch" -> UpgradeDeploymentStatelessResourceParametersPathStatelessResourceKindEnumAppsearch
                                            | val GHC.Classes.== "enterprise_search" -> UpgradeDeploymentStatelessResourceParametersPathStatelessResourceKindEnumEnterpriseSearch
                                            | val GHC.Classes.== "integrations_server" -> UpgradeDeploymentStatelessResourceParametersPathStatelessResourceKindEnumIntegrationsServer
                                            | GHC.Base.otherwise -> UpgradeDeploymentStatelessResourceParametersPathStatelessResourceKindOther val)
-- | Represents a response of the operation 'upgradeDeploymentStatelessResource'.
-- 
-- The response constructor is chosen by the status code of the response. If no case matches (no specific case for the response code, no range case, no default case), 'UpgradeDeploymentStatelessResourceResponseError' is used.
data UpgradeDeploymentStatelessResourceResponse =
   UpgradeDeploymentStatelessResourceResponseError GHC.Base.String -- ^ Means either no matching case available or a parse error
  | UpgradeDeploymentStatelessResourceResponse202 -- ^ The upgrade command was issued successfully. Use the \"GET\" command on the \/{deployment_id} resource to monitor progress
  | UpgradeDeploymentStatelessResourceResponse404 -- ^ * The Deployment specified by {deployment_id} cannot be found. (code: \`deployments.deployment_not_found\`) * The Resource specified by {ref_id} cannot be found. (code: \`deployments.deployment_resource_not_found\`)
  | UpgradeDeploymentStatelessResourceResponse449 -- ^ Elevated permissions are required. (code: \`root.unauthorized.rbac.elevated_permissions_required\`)
  deriving (GHC.Show.Show, GHC.Classes.Eq)
-- | > POST /deployments/{deployment_id}/{stateless_resource_kind}/{ref_id}/_upgrade
-- 
-- The same as 'upgradeDeploymentStatelessResource' but accepts an explicit configuration.
upgradeDeploymentStatelessResourceWithConfiguration :: forall m . Model/Private/Elasticsearch.Common.MonadHTTP m => Model/Private/Elasticsearch.Common.Configuration -- ^ The configuration to use in the request
  -> UpgradeDeploymentStatelessResourceParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> m (Network.HTTP.Client.Types.Response UpgradeDeploymentStatelessResourceResponse) -- ^ Monadic computation which returns the result of the operation
upgradeDeploymentStatelessResourceWithConfiguration config
                                                    parameters = GHC.Base.fmap (\response_4 -> GHC.Base.fmap (Data.Either.either UpgradeDeploymentStatelessResourceResponseError GHC.Base.id GHC.Base.. (\response body -> if | (\status_5 -> Network.HTTP.Types.Status.statusCode status_5 GHC.Classes.== 202) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right UpgradeDeploymentStatelessResourceResponse202
                                                                                                                                                                                                                              | (\status_6 -> Network.HTTP.Types.Status.statusCode status_6 GHC.Classes.== 404) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right UpgradeDeploymentStatelessResourceResponse404
                                                                                                                                                                                                                              | (\status_7 -> Network.HTTP.Types.Status.statusCode status_7 GHC.Classes.== 449) (Network.HTTP.Client.Types.responseStatus response) -> Data.Either.Right UpgradeDeploymentStatelessResourceResponse449
                                                                                                                                                                                                                              | GHC.Base.otherwise -> Data.Either.Left "Missing default response type") response_4) response_4) (Model/Private/Elasticsearch.Common.doCallWithConfiguration config (Data.Text.toUpper GHC.Base.$ Data.Text.pack "POST") (Data.Text.pack ("/deployments/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (upgradeDeploymentStatelessResourceParametersPathDeploymentId parameters))) GHC.Base.++ ("/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (upgradeDeploymentStatelessResourceParametersPathStatelessResourceKind parameters))) GHC.Base.++ ("/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (upgradeDeploymentStatelessResourceParametersPathRefId parameters))) GHC.Base.++ "/_upgrade"))))))) [Model/Private/Elasticsearch.Common.QueryParameter (Data.Text.pack "validate_only") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> upgradeDeploymentStatelessResourceParametersQueryValidateOnly parameters) (Data.Text.pack "form") GHC.Types.False])
-- | > POST /deployments/{deployment_id}/{stateless_resource_kind}/{ref_id}/_upgrade
-- 
-- The same as 'upgradeDeploymentStatelessResource' but returns the raw 'Data.ByteString.Char8.ByteString'.
upgradeDeploymentStatelessResourceRaw :: forall m . Model/Private/Elasticsearch.Common.MonadHTTP m => UpgradeDeploymentStatelessResourceParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> Model/Private/Elasticsearch.Common.ClientT m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.ByteString) -- ^ Monadic computation which returns the result of the operation
upgradeDeploymentStatelessResourceRaw parameters = GHC.Base.id (Model/Private/Elasticsearch.Common.doCallWithConfigurationM (Data.Text.toUpper GHC.Base.$ Data.Text.pack "POST") (Data.Text.pack ("/deployments/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (upgradeDeploymentStatelessResourceParametersPathDeploymentId parameters))) GHC.Base.++ ("/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (upgradeDeploymentStatelessResourceParametersPathStatelessResourceKind parameters))) GHC.Base.++ ("/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (upgradeDeploymentStatelessResourceParametersPathRefId parameters))) GHC.Base.++ "/_upgrade"))))))) [Model/Private/Elasticsearch.Common.QueryParameter (Data.Text.pack "validate_only") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> upgradeDeploymentStatelessResourceParametersQueryValidateOnly parameters) (Data.Text.pack "form") GHC.Types.False])
-- | > POST /deployments/{deployment_id}/{stateless_resource_kind}/{ref_id}/_upgrade
-- 
-- The same as 'upgradeDeploymentStatelessResource' but accepts an explicit configuration and returns the raw 'Data.ByteString.Char8.ByteString'.
upgradeDeploymentStatelessResourceWithConfigurationRaw :: forall m . Model/Private/Elasticsearch.Common.MonadHTTP m => Model/Private/Elasticsearch.Common.Configuration -- ^ The configuration to use in the request
  -> UpgradeDeploymentStatelessResourceParameters -- ^ Contains all available parameters of this operation (query and path parameters)
  -> m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.ByteString) -- ^ Monadic computation which returns the result of the operation
upgradeDeploymentStatelessResourceWithConfigurationRaw config
                                                       parameters = GHC.Base.id (Model/Private/Elasticsearch.Common.doCallWithConfiguration config (Data.Text.toUpper GHC.Base.$ Data.Text.pack "POST") (Data.Text.pack ("/deployments/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (upgradeDeploymentStatelessResourceParametersPathDeploymentId parameters))) GHC.Base.++ ("/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (upgradeDeploymentStatelessResourceParametersPathStatelessResourceKind parameters))) GHC.Base.++ ("/" GHC.Base.++ (Data.ByteString.Char8.unpack (Network.HTTP.Types.URI.urlEncode GHC.Types.True GHC.Base.$ (Data.ByteString.Char8.pack GHC.Base.$ Model/Private/Elasticsearch.Common.stringifyModel (upgradeDeploymentStatelessResourceParametersPathRefId parameters))) GHC.Base.++ "/_upgrade"))))))) [Model/Private/Elasticsearch.Common.QueryParameter (Data.Text.pack "validate_only") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> upgradeDeploymentStatelessResourceParametersQueryValidateOnly parameters) (Data.Text.pack "form") GHC.Types.False])
